# Generated by Django 5.1.2 on 2024-10-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycustomer',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
