# Generated by Django 5.1.2 on 2025-02-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_delete_loanitems'),
        ('users', '0002_alter_librarycustomer_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('overdue', 'Overdue'), ('lost', 'Lost')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_history', to='users.librarycustomer')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_history', to='catalogue.stockitem')),
            ],
            options={
                'ordering': ['-check_out_date'],
            },
        ),
        migrations.CreateModel(
            name='CurrentLoans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_loans', to='users.librarycustomer')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_loan', to='catalogue.stockitem')),
            ],
            options={
                'ordering': ['-loan_date'],
                'unique_together': {('customer', 'stock_item')},
            },
        ),
    ]
