# Generated by Django 5.1.2 on 2025-02-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_delete_loanitems'),
        ('users', '0003_loanhistory_currentloans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentLoans',
            new_name='CurrentLoan',
        ),
    ]
