# Generated by Django 5.1.2 on 2024-10-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=354, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_num', models.DecimalField(decimal_places=8, max_digits=10)),
                ('title', models.CharField(max_length=354)),
                ('author', models.CharField(max_length=128)),
                ('isbn', models.CharField(blank=True, max_length=15, null=True)),
                ('publication_year', models.DateField()),
                ('publisher', models.CharField(max_length=256)),
                ('subjects', models.TextField()),
                ('item_type', models.CharField(max_length=128)),
                ('item_Collection', models.CharField(max_length=128)),
                ('floating_item', models.BooleanField()),
                ('item_location', models.CharField(max_length=128)),
                ('report_date', models.DateField()),
                ('item_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('street_address1', models.CharField(max_length=256)),
                ('street_address2', models.CharField(blank=True, max_length=256, null=True)),
                ('city_or_town', models.CharField(max_length=256)),
                ('postcode', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('email_address', models.CharField(max_length=256)),
                ('is_child', models.BooleanField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
