# Generated by Django 5.1.2 on 2024-10-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('BibNum', models.CharField(primary_key=True, max_length=256)),
                ('Title', models.CharField(max_length=512)),
                ('Author', models.CharField(max_length=512)),
                ('ISBN', models.CharField(blank=True, max_length=256, null=True)),
                ('PublicationYear', models.CharField(blank=True, max_length=256, null=True)),
                ('Publisher', models.CharField(max_length=256)),
                ('Subjects', models.CharField(max_length=256)),
                ('ItemType', models.CharField(max_length=128)),
                ('ItemCollection', models.CharField(max_length=128)),
                ('FloatingItem', models.CharField(blank=True, max_length=256, null=True)),
                ('ItemLocation', models.CharField(max_length=128)),
                ('ReportDate', models.CharField(max_length=256)),
                ('ItemCount', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
