# Generated by Django 5.1.2 on 2024-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BibNum', models.IntegerField()),
                ('Title', models.CharField(max_length=512)),
                ('Author', models.CharField(max_length=512)),
                ('ISBN', models.CharField(blank=True, max_length=256, null=True)),
                ('PublicationYear', models.IntegerField()),
                ('Publisher', models.CharField(max_length=256)),
                ('Subjects', models.TextField()),
                ('ItemType', models.CharField(max_length=128)),
                ('ItemCollection', models.CharField(max_length=128)),
                ('FloatingItem', models.CharField(blank=True, max_length=256, null=True)),
                ('ItemLocation', models.CharField(max_length=128)),
                ('ReportDate', models.DateField()),
                ('ItemCount', models.IntegerField(default=0)),
            ],
        ),
    ]
