# Generated by Django 5.1.2 on 2024-10-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_stockitem_itemcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='BibNum',
            field=models.CharField(max_length=256),
        ),
    ]
