# Generated by Django 5.1.2 on 2024-10-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_catalogueitem_bibnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='StockID',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
