# Generated by Django 5.1.2 on 2024-10-27 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_remove_catalogueitem_id_alter_catalogueitem_bibnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='ItemCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('StockID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalogue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalogue.catalogueitem')),
            ],
        ),
    ]
