# Generated by Django 5.1.2 on 2024-11-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_catalogueitem_itemcount_stockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='FloatingItem',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='ISBN',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='ItemCollection',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='ItemLocation',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='ItemType',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='PublicationYear',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='Publisher',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='ReportDate',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='Subjects',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='Title',
            field=models.CharField(max_length=1024),
        ),
    ]
