# Generated by Django 5.1.2 on 2025-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_alter_catalogueitem_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='Status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
