# Generated by Django 5.1.2 on 2025-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_stockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='Location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
