# Generated by Django 5.1.2 on 2025-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_stockitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='Borrower',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
