# Generated by Django 5.1.2 on 2025-02-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_stockitem_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
