# Generated by Django 5.1.2 on 2025-02-02 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_stockitem_last_updated'),
        ('users', '0002_alter_librarycustomer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='Status',
            field=models.CharField(choices=[('active', 'Active'), ('in branch', 'In Branch'), ('overdue', 'Overdue'), ('maintenance', 'Maintenance'), ('discarded', 'Discarded'), ('missing', 'Missing')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='LoanItems',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_out_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in branch', 'In Branch'), ('overdue', 'Overdue'), ('maintenance', 'Maintenance'), ('discarded', 'Discarded'), ('missing', 'Missing')], max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.librarycustomer')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='catalogue.stockitem')),
            ],
            options={
                'ordering': ['-check_out_date'],
            },
        ),
    ]
