# Generated by Django 5.1.2 on 2025-02-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_alter_loanitems_status_alter_stockitem_status'),
        ('users', '0002_alter_librarycustomer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanitems',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_history', to='users.librarycustomer'),
        ),
        migrations.AlterField(
            model_name='loanitems',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_history', to='catalogue.stockitem'),
        ),
    ]
