# Generated by Django 5.1.2 on 2025-02-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_alter_loanitems_borrower_alter_loanitems_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanitems',
            name='status',
            field=models.CharField(choices=[('on_loan', 'On Loan'), ('available', 'Available'), ('overdue', 'Overdue'), ('maintenance', 'Maintenance'), ('discarded', 'Discarded'), ('missing', 'Missing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='Status',
            field=models.CharField(choices=[('on_loan', 'On Loan'), ('available', 'Available'), ('overdue', 'Overdue'), ('maintenance', 'Maintenance'), ('discarded', 'Discarded'), ('missing', 'Missing')], max_length=20, null=True),
        ),
    ]
