# Generated by Django 5.1.2 on 2025-02-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_alter_loanitems_status_alter_stockitem_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanItems',
        ),
    ]
